server:
  port: 81
spring:
  application:
    name: common-service # 应用名称
  redis:
    # redisson
    redisson:
      mode: single
      password: 123456a
      config:
        # Redisson 配置
        singleServerConfig:
          address: "redis://127.0.0.1:6379"
          password: 123456
          clientName: null
          database: 15 #选择使用哪个数据库0~15
          idleConnectionTimeout: 10000
          pingTimeout: 1000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          reconnectionTimeout: 3000
          failedAttempts: 3
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000
          #dnsMonitoring: false

        threads: 0
        nettyThreads: 0
        codec:
          class: "org.redisson.codec.JsonJacksonCodec"
        transportMode: "NIO"