server:
  port: 9090 # 端口

spring:
  application:
    name: order-service # 应用名称
  # 配置 Nacos 注册中心
  cloud:
    nacos:
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现，设置为 false 即可
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nacos_demo?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&ssl=true
    username: root
    password: 123456
  #redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
  session:
    redis:
      #设置存储格式
      namespace: spring::session
      #设置session刷新ON_SAVE（表示在response commit前刷新缓存），IMMEDIATE（表示只要有更新，就刷新缓存）
      flush-mode: on_save
    # 选择使用redis 作为session存储
    store-type: redis
    #设置session超时时间
    timeout: 1200s
swagger:
  enable: true
  application-name: 鉴权配置中心接口-order
  application-version: 1.0
  application-description: 鉴权配置中心
# 不校验白名单
ignore:
  whites:
    - /logout
    - /login
    - /*/v2/api-docs
    - /csrf
    - /v3/api-docs
    - /swagger-ui/index.html
##mybatis-plus mapper xml 文件地址
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  ##mybatis-plus type-aliases 文件地址
  type-aliases-package: com.example.entity